name: Buscar Noticia del Athletic Club

on:
  schedule:
    - cron: '*/15 7-11 * * *'
  workflow_dispatch:

jobs:
  buscar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt
      
      - name: Ejecutar script de b칰squeda
        id: busqueda
        run: python buscar_noticia.py > resultado.txt

      - name: Leer resultado
        id: leer_resultado
        run: echo "resultado=$(cat resultado.txt)" >> $GITHUB_OUTPUT
      
      # ----- PASO MODIFICADO AQU칈 -----
      - name: Enviar notificaci칩n por Telegram
        # Se ejecuta solo si el resultado fue 'true'
        if: steps.leer_resultado.outputs.resultado == 'true'
        # Usamos una acci칩n popular para Telegram
        uses: appleboy/telegram-action@master
        with:
          # Usamos los Secrets que acabamos de crear
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # Mensaje que recibir치s. Puedes personalizarlo como quieras.
          message: |
            游부 Noticias sobre el partido del Newcastle! 游부
            
            El script ha encontrado una noticia que menciona a "Newcastle".
            
            Revisa la web aqu칤: https://www.athletic-club.eus/noticias/club/1
