name: Buscar Noticia del Athletic Club

on:
  schedule:
    - cron: '*/15 7-11 * * *'
  workflow_dispatch:

jobs:
  buscar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt
      
      - name: Ejecutar script de b칰squeda
        id: busqueda
        run: python main.py > resultado.txt

      - name: Leer resultado
        id: leer_resultado
        run: echo "resultado=$(cat resultado.txt)" >> $GITHUB_OUTPUT
      
      - name: Enviar notificaci칩n por Telegram si hay nuevos partidos
        if: steps.leer_resultado.outputs.resultado != ''
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            游부 춰Nuevas noticias del Athletic Club! 游부
            
            Se han encontrado noticias sobre los siguientes equipos: *${{ steps.leer_resultado.outputs.resultado }}*
            
            Revisa la web aqu칤: https://www.athletic-club.eus/noticias/club/1

      # ----- PASOS NUEVOS PARA GUARDAR LA "MEMORIA" -----
      - name: Guardar cambios en el repositorio
        # Este paso solo se ejecuta si se encontraron nuevos equipos
        if: steps.leer_resultado.outputs.resultado != ''
        run: |
          # Configuramos Git para poder hacer commits
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # A침adimos el archivo de estado al commit
          git add notified_teams.txt
          # Hacemos el commit solo si hay cambios
          git commit -m "CI: Actualiza la lista de equipos notificados" || echo "No hay cambios que guardar."
          # Subimos los cambios al repositorio
          git push
